# -*- coding: utf-8 -*-
"""removing_null_value_rows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXSfzY-6SnZg57nBSNX10cblhAOOs9YC
"""



import pandas as pd

data=pd.read_csv("/googleplaystore.csv")

data.head(10)

data.isnull().sum()

df=data.dropna()

df.isnull().sum()

