# -*- coding: utf-8 -*-
"""data_analysis(numeric).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXSfzY-6SnZg57nBSNX10cblhAOOs9YC
"""



import pandas as pd

data=pd.read_csv("/googleplaystore.csv")

data.head(10)

data.isnull().sum()

dk=data.dropna()

dk.isnull().sum()

# Findinf the average rating

dk['Rating']

sum=int(sum(dk['Rating']))

avg_rating=sum/(len(dk['Rating']))
a=float(str(avg_rating)[:4])
print("The average rating of apps is: ",a)

s=0
for i in dk['Rating']:
  s+=i
s

avg=s/len(dk['Rating'])
print("The average rating of apps is: ",float(str(avg)[:4]))

## How many apps are there with rating 5

s=0
for i in dk['Rating']:
  if i==5.0:
    s+=1
print("The number of apps with rating 5 is: ",s)

## how many apps are there with ration is between 4 to 4.5

s=0
for i in data['Rating']:
  if (i>=4 and i<=4.5):
    s+=1
print("There are ",s," apps with rating in between 4 to 4.5")

