# -*- coding: utf-8 -*-
"""Data Analysis-Categorical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PHWfnv0ahrrRcGv-eljJixeYhWxLSv9
"""

import pandas as pd

df=pd.read_csv('/googleplaystore.csv').dropna()

df.head(10)

## Total number of categories

len(df['Category'].unique())

## Total number of apps in category art and design

s=0
for i in df['Category']:
    if i== 'ART_AND_DESIGN':
      s+=1
print("The total nmber of app in art and design in",s)

# Total types of aaps
df['Type'].unique()

## total free and paid applications

f=0
p=0
for i in df['Type']:
  if i=='Free':
    f+=1
  else:
    p+=1
print("The total number of free apps are",f)
print("The total number of paid apps are",p)

# total percent of free apps
fp=(f/(f+p))*100
print(int(fp),"% apps are free")

# name all the content rating
for i in df["Content Rating"].unique():
  print(i)