# -*- coding: utf-8 -*-
"""Data analysis with multipe columns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raAdMziAluPM8dRd6j6A4Fg3v-Lufwu6
"""

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=pd.read_csv('/content/googleplaystore (1).csv')
df

df=df.dropna()
df.isna().sum()

# HoW many free apps are there in arts and design

df=df.values

ct=0
for i in df:
  if i[1]=='ART_AND_DESIGN' and i[6]=='Free':
    ct+=1
print("There are",ct,"free apps are there in arts and design")

# HoW many paid apps are there in arts and design
ct=0
for i in df:
  if i[1]=='ART_AND_DESIGN' and i[6]=='Paid':
    ct+=1
print("There are",ct,"Paid apps are there in arts and design")

# HoW manye apps are there in arts and design with the rating more than 4.5
ct=0
for i in df:
  if i[1]=='ART_AND_DESIGN' and i[2]>4.5:
    ct+=1
print("There are",ct," apps in arts and design with rating more than 4.5")

"""How many apps are there in art and design with rating more than 4.5?

"""

ct=0
for i in df:
  if i[1]=='ART_AND_DESIGN' and i[6]=='Free' and i[2]>4.5:
    ct+=1
print("There are",ct,"Paid apps are there in ART AND DESIGN with rating more than 4.5")

"""List all the free apps in family with rating more than 4.5?"""

ct=[]
for i in df:
  if i[1]=='ART_AND_DESIGN' and i[6]=='Free' and i[2]>4.5:
    ct.append(i[0])
print("The apps in family category with rating more than 4.5 are:")
print("*"*100)
print(ct)
len(ct)