# -*- coding: utf-8 -*-
"""Data analysis using conditions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raAdMziAluPM8dRd6j6A4Fg3v-Lufwu6
"""

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=pd.read_csv('/content/googleplaystore (1).csv')
df

# HoW many free apps are there in arts and design

dp=df[df['Category'] =='ART_AND_DESIGN']

f_art=dp[dp['Type']=="Free"]

len(f_art)

# HoW many paid apps are there in arts and design
f_art=len(dp[dp['Type']=="Paid"])
print('There are', f_art, "paid apps in art and design")

# HoW manye apps are there in arts and design with the rating more than 4.5
len(dp[dp['Rating']>4.5])

"""How many free apps are there in FAmily category with rating more than 4.5?

"""

dr=df[df['Category']=='Family']
dr=dr[dr['Type']=='Paid']
len(dr[dr['Rating']>4.5])

"""List all the free apps in family with rating more than 4.5?"""

dr=df[df['Category']=='Family']
dr=dr[dr['Type']=='Free']
dr=dr[dr['Rating']>4.5]
res=dr.values
for i in res:
  print(i[0])