# -*- coding: utf-8 -*-
"""Data analysis using Groupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raAdMziAluPM8dRd6j6A4Fg3v-Lufwu6
"""

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

df=pd.read_csv('/content/googleplaystore (1).csv')
df

df=df.dropna()
df.isna().sum()

"""name the apps in art and design with rating more than 4.5 in ascending order WRT Ratings.






---


"""

df_pr=df[df['Category']=='ART_AND_DESIGN']
df_pr=df_pr[df_pr['Rating']>4.5]
df_pr.sort_values(by= 'Rating',ascending=True).head()

"""name the apps in art and design  in decending order WRT Reviews[link text](https://)

"""

df_pr=df[df['Category']=='ART_AND_DESIGN']
df_pr.sort_values(by= 'Reviews',ascending=True)

"""Which category is having  average rating in decending order."""

df.groupby('Category').mean('Rating').sort_values(by='Rating',ascending=False)

"""How many free apps are there in each of the categories?"""

d_f=df[df['Type']=='Free']
d_f.groupby('Category').count()['Type'].sort_values(ascending=False)