# -*- coding: utf-8 -*-
"""5null values handling-Numeric.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4g_fvYQHYOcedeL3xd7ttbkmydUeLPQ
"""

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

df=pd.read_csv("/content/Data (1).csv")

df

#Removing the rows
df.dropna()

df

# imputers
#mean

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
a=df.iloc[:,1:3]=imputer.fit_transform(df.iloc[:,1:3])

for i in a:
  print(i)

df

#Mode|most_frequent
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')



df.iloc[:,1:3]=imputer.fit_transform(df.iloc[:,1:3])

df