# -*- coding: utf-8 -*-
"""5null values handling-Categorical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4g_fvYQHYOcedeL3xd7ttbkmydUeLPQ
"""

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

df=pd.read_csv("/content/Data (2).csv")

df

imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

a=df.iloc[:,0:4]
a=imputer.fit_transform(df.iloc[:,0:4])
df